### ISSUE TITLE
部分情况下 kimpanel 顶栏图标有问题.

### ISSUE THREAD

**Issue by lixiaoyan** [wengxt/kimpanel-for-gnome-shell#28]
![screenshot from 2015-10-08 15-39-36](https://cloud.githubusercontent.com/assets/1610614/10360394/f4b918c6-6dd2-11e5-81c6-6fe0db2dab16.png)

比如在 gnome-terminal 或者 gnome 的搜索框, 顶栏 kimpanel 的图标会显示为这样上对齐的 us 文字.

**Comment by wengxt** [comment]
ˊ_>ˋ 显示 us 没啥问题吧
除了你觉得位置不太对？

**Comment by lixiaoyan** [comment]
位置是一个, 另外一个就是宽度来回跳...

**Comment by wengxt** [comment]
这什么主题，我用默认主题没发现很大问题

**Comment by lixiaoyan** [comment]
Arc-Theme, 换回默认 theme 在切换输入法时仍有宽度变化.

**Comment by wsxy162** [comment]
不懂 JavaScript，看到另外一个扩展也碰到这个问题，有人提供了解决方法。我就依葫芦画瓢吧

@@ -2,4 +2,5 @@
 const PanelMenu = imports.ui.panelMenu;
 const PopupMenu = imports.ui.popupMenu;
+const Clutter = imports.gi.Clutter;
 const Params = imports.misc.params;
 const Shell = imports.gi.Shell;
@@ -22,5 +23,5 @@
         this._box = new St.BoxLayout({ style_class: 'panel-status-menu-box' });
-        this.labelIcon = new St.Label({ style_class: 'system-status-icon' });
+        this.labelIcon = new St.Label({ style_class: 'system-status-icon', y_align: Clutter.ActorAlign.CENTER });
         this.mainIcon = new St.Icon({ gicon: Lib.createIcon('input-keyboard'),
                                  style_class: 'system-status-icon' });

这样显示 us/cn 就会垂直对齐了。宽度我觉得是下拉图标的问题，下拉图标造成整体图标不够紧凑。

**Comment by wsxy162** [comment]
宽度在激活/非激活输入法时会有变化，应该还是这个语言标签的问题。在输入法间切换宽度就不会变化。
