### ISSUE TITLE
fcitx-sogou 的不兼容

### ISSUE THREAD

**Issue by wsxy162** [wengxt/kimpanel-for-gnome-shell#32]
切换到搜狗输入法后，打字的时候出现乱码，出现两个输入面板。是因为 fcitx 自己写了个 qimpanel 覆盖了原本 panel 界面吗？这边的扩展能再次覆盖掉这个分离的搜狗界面吗？不喜欢寄人篱下还搞独立的做法。

**Comment by petronny** [comment]
我也遇到了这个问题。请问fcitx-sogoupinyin自己的面板有什么办法处理掉呢？

**Comment by WordlessEcho** [comment]
Problem doesn't be solved, reopen this issue again, please.

**Comment by wsxy162** [comment]
我认为是搜狗方面的问题，自己改了很多东西，无法兼容上流项目。这个问题应该找搜狗公司。

**Comment by WordlessEcho** [comment]
Now Sogou Pinyin will show double candidate box (one show at top-left) instand of funny charact.
![screenshot from 2018-10-28 16-52-12](https://user-images.githubusercontent.com/12007025/47613891-f3e9b580-dad1-11e8-99ee-04665244cbb6.png)

**Comment by metorm** [comment]
@WordlessEcho I am faced with the same problem, have you worked this out?

**Comment by WordlessEcho** [comment]
@metorm No.
