### ISSUE TITLE
Please add support for Gnome 3.24

### ISSUE THREAD

**Issue by warmsun0220** [wengxt/kimpanel-for-gnome-shell#34]
Please add support for Gnome 3.24, thanks

**Comment by wengxt** [comment]
I heard it is not really required to bump version, is that true?

**Comment by wengxt** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=770887 claims no need to update version anymore.

Arch Linux doesn't have 3.24 for now, once its hit the repo I'll check if it works.

**Comment by warmsun0220** [comment]
I tried it in gnome 3.24 +archlinux X64, it can not be enabled.

**Comment by wsxy162** [comment]
The first version of new GNOME comes in Arch stable repo usually is X.1 mirror version, so there is more than two weeks to waitting for.

**Comment by wengxt** [comment]
well, you can still add 3.24 to the metadata.json to see if it works.

**Comment by wsxy162** [comment]
Tried it, does't work. Before that, the extension was marked with a "Error" tag in the installed list on the website. Now the extension is gone from the list even I reinstalled it.

**Comment by Sherlock-Holo** [comment]
https://github.com/wengxt/kimpanel-for-gnome-shell/commit/d3de8bb6d1b784510e07fb701ffa6ebac0eb4b12
it works well on gnome 3.24 Arch Linux
